### ISSUE TITLE
nuxt.config.ts配置一直报ts错误

### ISSUE THREAD

**Issue by xxwangkaimin** [yunyuyuan/nuxt3-blog#17]
作者你好，我在用nuxt3初始化项目之后，在nuxt.config.ts中写配置的时候一直报TS的错误，不管写什么配置都报错，而且没有任何代码提示，但是不影响项目运行。报错如下图
![image](https://user-images.githubusercontent.com/33536543/230516903-467237a7-6663-4530-a3c2-998b19b388ad.png)
而且我在GitHub上下载下来的项目是没有这个报错的。
想问一下，这个是怎么处理的？

**Comment by yunyuyuan** [comment]
你好，可能是你的项目没有正确生成.nuxt文件夹，或者webstorm对nuxt支持不友好，换vscode试试呢
