### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 7nuns** [yunyuyuan/nuxt3-blog#26]
输入 GitHub token 的时候报这个错是什么原因呢 Error: [object Object]

**Comment by yunyuyuan** [comment]
应该网络问题，可以F12打开控制台再输入token，看这条请求报的啥错误
![image](https://github.com/yunyuyuan/nuxt3-blog/assets/45785585/3b777b81-d5ae-44ff-b9be-a4b32a43dec6)

**Comment by 7nuns** [comment]
感谢回复，是这样的报错。
我需要重装试一下吗
![Uploading image.png…]()

**Comment by yunyuyuan** [comment]
@7nuns 你的图片没有上传成功，看不到

**Comment by 7nuns** [comment]
<img width="1426" alt="image" src="https://github.com/yunyuyuan/nuxt3-blog/assets/147688965/fcea0481-f374-409e-8b5b-fcf037df3cba">

**Comment by yunyuyuan** [comment]
@7nuns 你fork的时候改了仓库名，需要同步更改config.ts里的githubRepo  https://github.com/7nuns/7nuns-web/blob/master/config.ts#L38

**Comment by 7nuns** [comment]
醍醐灌顶，谢谢大佬
