### ISSUE TITLE
你好大佬，我发现你这个导航是多选的好像不太好格式

### ISSUE THREAD

**Issue by xinkeji** [yunyuyuan/nuxt3-blog#28]
多选还是要多一些才能用，就目前来说随便选两个好像就没有文章

**Comment by yunyuyuan** [comment]
是的，多选的时候大概率是空的，你有啥好的想法嘛

**Comment by xinkeji** [comment]
直接用标签不行吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunyuyuan/nuxt3-blog] 你好大佬，我发现你这个导航是多选的好像不太好格式 (Issue #28)




 
是的，多选的时候大概率是空的，你有啥好的想法嘛

**Comment by xinkeji** [comment]
或者直接就超链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunyuyuan/nuxt3-blog] 你好大佬，我发现你这个导航是多选的好像不太好格式 (Issue #28)




 
是的，多选的时候大概率是空的，你有啥好的想法嘛

**Comment by yunyuyuan** [comment]
@xinkeji 去掉多选功能吗

**Comment by xinkeji** [comment]
是的没必要多选



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yunyuyuan/nuxt3-blog] 你好大佬，我发现你这个导航是多选的好像不太好格式 (Issue #28)




 
@xinkeji 去掉多选功能吗
