### ISSUE TITLE
关于编写文章时，enter切换行，自动返回到第一行

### ISSUE THREAD

**Issue by chenryace** [yunyuyuan/nuxt3-blog#6]
大佬，感谢您的编译，正在尝试，但是出现了一点bug
**编写文章时，enter切换行，自动返回到第一行**
输入结束后，按tab的话可以正常用，就是会多出1空行出来。

**Comment by yunyuyuan** [comment]
[fixed](https://github.com/yunyuyuan/nuxt3-blog/commit/9ee947bdbbb5ff573126232efa26a3f31e816bab)

**Comment by yunyuyuan** [comment]
没看懂，空出一行是什么意思呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yunyuyuan/nuxt3-blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 凌晨2:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yunyuyuan/nuxt3-blog] 关于编写文章时，enter切换行，自动返回到第一行 (Issue #6)





 
大佬，感谢您的编译，正在尝试，但是出现了一点bug
 编写文章时，enter切换行，自动返回到第一行
 输入结束后，按tab的话可以正常用，就是会多出1空行出来。
